SASS-2990 FE DELETE Orchestration
hmrc/income-tax-cis-frontend pull request #53
Opened 2022-06-13 08:58 UTC by BenCosfordHMRC

https://jira.tools.tax.service.gov.uk/browse/SASS-2902

### Checklist PR Reviewer
##### Before Reviewing
- [ ]  Have you pulled the branch down?
- [ ]  Have you assigned yourself to the PR?
- [ ]  Have you moved the task to “in review” on JIRA?
- [ ]  Have you checked to ensure all dependencies are up to date?
- [ ]  Have you checked to ensure its been rebased against the current version of main?

##### Whilst Reviewing
- [ ]  Have you run the tests?
- [ ]  Have you run the journey tests?
- [ ]  Have you looked at the JIRA story to make sure all Acceptance Criteria has been met?

##### After Reviewing
- [ ]  Have you checked for merge conflicts or any changes in the current main that may affect the current pull request? i.e. does it need another rebase?
- [ ]  Have you checked to make sure there are no builds in the pipeline before you merge?
- [ ]  Have you moved the task to “in pipeline” on Jira?

### Checklist PR Raiser
##### Before creating PR
- [ ]  Have you run the tests?
- [ ]  Have you run the journey tests? (where applicable)
- [ ]  Have you addressed warnings where appropriate?
- [ ]  Have you rebased against the current version of main?
- [ ]  Have you checked code coverage isn’t lower than previously?

##### After PRs been raised
- [ ]  Have you checked the PR Builder passes?

2022-06-20 09:15 UTC, ina-tu requested changes
needs a rebase

2022-06-20 12:39 UTC, BenCosfordHMRC commented on it/connectors/CISConnectorSpec.scala
> +      Seq(BAD_REQUEST, NOT_FOUND, INTERNAL_SERVER_ERROR, SERVICE_UNAVAILABLE).foreach { status =>
The parsers should all have service unavailable on them so I've added cases for them.

2022-06-20 14:28 UTC, ina-tu commented on it/controllers/ContractorCYAControllerISpec.scala
> +  private val anUpdateCISSubmission: CISSubmission = aCreateCISSubmission.copy(
the builder for the update can be used here instead of using .copy on aCreateCISSubmission

2022-06-20 14:34 UTC, ina-tu commented on test/support/builders/models/submission/CISSubmissionBuilder.scala
> +  val aCreateCISSubmission: CISSubmission = CISSubmission(
would it better to have one val for CISSubmissionBuilder and then create vals in tests where it's used, similar to the other tests?

2022-06-20 14:43 UTC, ina-tu commented on test/services/DeleteCISPeriodServiceSpec.scala
> +
are these all supposed to be in the same test?

2022-06-21 09:38 UTC, ina-tu approved these changes

2022-06-21 12:19 UTC, merged