SASS-3191: Check your CIS deductions changes.
hmrc/income-tax-cis-frontend pull request #63
Opened 2022-08-24 09:57 UTC by srinivas-hmrc

### Description
Please include a brief summary of the change you've made and the issue that it fixes.

Add a link to the relevant story in Jira
[SASS-3191](https://jira.tools.tax.service.gov.uk/browse/SASS-3191)

### Checklist PR Reviewer
##### Before Reviewing
- [ ]  Have you pulled the branch down?
- [ ]  Have you assigned yourself to the PR?
- [ ]  Have you moved the task to “in review” on JIRA?
- [ ]  Have you checked to ensure all dependencies are up to date?
- [ ]  Have you checked to ensure its been rebased against the current version of main?

##### Whilst Reviewing
- [ ]  Have you run the tests?
- [ ]  Have you run the journey tests?
- [ ]  Have you looked at the JIRA story to make sure all Acceptance Criteria has been met?

##### After Reviewing
- [ ]  Have you checked for merge conflicts or any changes in the current main that may affect the current pull request? i.e. does it need another rebase?
- [ ]  Have you checked to make sure there are no builds in the pipeline before you merge?
- [ ]  Have you moved the task to “in pipeline” on Jira?

### Checklist PR Raiser
##### Before creating PR
- [x]  Have you run the tests?
- [x]  Have you run the journey tests? (where applicable)
- [x]  Have you addressed warnings where appropriate?
- [ ]  Have you rebased against the current version of main?
- [x]  Have you checked code coverage isn’t lower than previously?

##### After PRs been raised
- [ ]  Have you checked the PR Builder passes?

2022-08-24 14:44 UTC, georgievh commented
Please update the following libraries:|
![image](https://user-images.githubusercontent.com/2192407/186448507-27d48f11-a499-4bf8-88c9-3a14b5171de4.png)

2022-08-24 16:12 UTC, georgievh requested changes

2022-08-24 16:12 UTC, georgievh commented on test/actions/ActionsProviderSpec.scala
> +    "redirect to CisUser data finished urls" should {
You already tested all of this in CisUserDataFinishedFilterActionSpec. You don't need to test the same thing twice. The only think you need to test here is that the new action is part of the actions composition. One happy case is enough.

2022-08-24 16:12 UTC, georgievh commented on test/actions/ActionsProviderSpec.scala
> +        val viewNrsPayload = ViewCisPeriodPayload(
You are not testing NRS here. A different test is needed for that. This needs to be removed. Further, we should not create objects like that in the tests. We should be using builders instead. When there is no builder created, it should be created and used.

2022-08-24 16:12 UTC, georgievh commented on test/actions/ActionsProviderSpec.scala
> +        val viewNrsPayload = ViewCisPeriodPayload(
I think it might be better if we pair a bit to address those. Especially in relation to the ActionsProviderSpec.

2022-08-25 09:08 UTC, srinivas-hmrc commented on test/actions/CisUserDataFinishedFilterActionSpec.scala
> +    "return a redirect to same page when finished the Filter Action" in {
updated

2022-08-25 09:08 UTC, srinivas-hmrc commented on test/actions/CisUserDataFinishedFilterActionSpec.scala
> +    "return a redirect to ContractorDetails url when it is not PriorSubmission and costOfMaterials were not provided" in {
updated

2022-08-25 19:48 UTC, georgievh requested changes

2022-08-25 19:48 UTC, georgievh commented on test/actions/ActionsProviderSpec.scala
> +      val viewNrsPayload = aViewCisPeriodPayload.copy(contractorDetails = ContractorDetails(name = Some("ABC Steelworks"), ern = "some-ref"))
ContractorDetails should have a builder too. Please use that builder here.

2022-08-25 19:48 UTC, georgievh commented on test/actions/ActionsProviderSpec.scala
> +      val viewNrsPayload = aViewCisPeriodPayload.copy(contractorDetails = ContractorDetails(aCisDeductions.contractorName, "some-ref"))
Same as above.

2022-08-25 19:48 UTC, georgievh commented on test/support/builders/models/nrs/DeductionPeriodBuilder.scala
> +  val aCustomerDeductionPeriod = DeductionPeriod(
This should be named: aDeductionPeriod since you are using DeductionPeriodBuilder.

2022-08-25 19:48 UTC, georgievh commented on test/support/builders/models/nrs/ViewCisPeriodPayloadBuilder.scala
> +    DeductionPeriod(
Use a builder.

2022-08-26 11:47 UTC, georgievh approved these changes

2022-08-26 11:47 UTC, merged